# Generated by Django 3.2.16 on 2023-06-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='идентификатор игрока')),
                ('main_alias', models.CharField(max_length=255, verbose_name='Основное имя игрока')),
                ('other_aliases', models.CharField(blank=True, max_length=255, null=True, verbose_name='Другие имена игрока')),
                ('telegram_login', models.CharField(blank=True, max_length=100, null=True, verbose_name='Логин Telegram')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона игрока')),
                ('banks', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер карты или счета')),
            ],
        ),
    ]
