# Generated by Django 3.2.16 on 2023-06-23 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='идентификатор игры')),
                ('url', models.CharField(max_length=255, verbose_name='URL игры')),
                ('ledger', models.CharField(blank=True, max_length=255, null=True, verbose_name='??????')),
                ('picture', models.ImageField(blank=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='идентификатор команды')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='players.player')),
                ('players', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='players.player')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='идентификатор игры')),
                ('value', models.FloatField(blank=True, max_length=30, null=True, verbose_name='Значение суммы платежа')),
                ('paid', models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Оплачено')),
                ('received', models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Оплата получена')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Игра', to='players.game')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Игрок', to='players.player')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Players', to='players.player')),
            ],
            options={
                'verbose_name': 'Оплата',
                'verbose_name_plural': 'Оплаты',
            },
        ),
    ]
