# Generated by Django 3.2.16 on 2023-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_game_payment_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='game',
            field=models.ManyToManyField(related_name='games', to='players.Game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='ledger',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='расчеты'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='admin',
        ),
        migrations.AddField(
            model_name='team',
            name='admin',
            field=models.ManyToManyField(related_name='admin', to='players.Player'),
        ),
        migrations.RemoveField(
            model_name='team',
            name='players',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(related_name='players', to='players.Player'),
        ),
    ]
