# Generated by Django 3.2.16 on 2023-06-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_auto_20230625_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='admin',
            field=models.ManyToManyField(related_name='administrator', to='players.Player'),
        ),
    ]
