# Generated by Django 3.2.16 on 2023-06-25 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_auto_20230625_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.player', verbose_name='Игрок'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='players.player', verbose_name='Получатель'),
        ),
    ]
