# Generated by Django 3.2.16 on 2023-06-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0007_auto_20230625_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(default=False, max_length=10, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received',
            field=models.BooleanField(default=False, max_length=10, verbose_name='Оплата получена'),
        ),
    ]
