# Generated by Django 3.2.16 on 2023-06-25 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_auto_20230625_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Оплачено'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='received',
            field=models.BooleanField(blank=True, max_length=10, null=True, verbose_name='Оплата получена'),
        ),
    ]
